### ISSUE TITLE
Compatibility with parsleyjs 2.0

### ISSUE THREAD

**Issue by martez81** [johannes-gehrs/wtforms-parsleyjs#10]
Right of the bat wtforms-parsleyjs does not work with parsleyjs 2.0 due to changes to default attribute namespace. In order to adjust that form tag needs to define a remap for namespace e.g. `data-parsley-namespace="parsley-"`.

**Comment by SmileyJames** [comment]
We have dealt with this differently, all the Python code in this fork used "data-parsley" namespace instead of the original repo that I assume uses the old "parsley-" namespace.

In the future I wish to add a namespace variable in the python code so that it can be changed in both the JavaScript and the Python code, however I have yet to find the time.

**Comment by johannes-gehrs** [comment]
This tool is currently not compatible with Parsley JS 2.0. I am also not sure if it works with the most current WTForms versions. Sorry, it has been poorly maintained.

**Comment by SmileyJames** [comment]
Sorry @martez81 I though you were on a different fork, apologies. As @fuhrysteve said in the other issue checkout https://github.com/fuhrysteve/wtforms-parsleyjs, I have contributed a lot to that fork hence the confusion.
